### PR TITLE
Add "Married to non-staff" to enum

### PR DESCRIPTION
**Pull request by knutsenm**
Presumably must add this to the enum values in GR as well.

### CODE REVIEW

**Comment by Omicron7** [comment]
👍

**Comment by knutsenm** [comment]
@Omicron7 how to tweak the api side to accept and store this new value but stow "Married" in GR? That might be nicer.

**Comment by Omicron7** [comment]
https://github.com/CruGlobal/global-profile-api/blob/master/app/models/person.rb#L46
You'll need to serialize the value to Married instead of just passing it to GR as is.

**Comment by Omicron7** [comment]
👍

**Comment by knutsenm** [comment]
Spot checked in staging; works well. Will deploy tomorrow.

**Pull request merged**
